11/06/2016 04:08:28 - app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nikita/develop/flask_project/logapp/app/views.py", line 9, in index
    i = 1 / 0
ZeroDivisionError: integer division or modulo by zero
11/06/2016 04:20:38 - app - ERROR - Exception on /datareceiver [POST]
Traceback (most recent call last):
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nikita/develop/flask_project/logapp/app/views.py", line 22, in equipments
    logger.info(json.dumps(data, sort_keys=True, ident=4))
  File "/usr/lib/python2.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'ident'
11/06/2016 04:21:50 - app - ERROR - Exception on /datareceiver [POST]
Traceback (most recent call last):
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nikita/develop/flask_project/logapp/env/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nikita/develop/flask_project/logapp/app/views.py", line 22, in equipments
    logger.info(json.dumps(data, sort_keys=True, indent=4))
  File "/usr/lib/python2.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'ident'
